
export * from './phoneIcon'
export * from './callRingIcong'
export * from './emailIcon'
export * from './locationIcon'

export * from './wranchIcon'
export * from './portfolioIcon'
export * from './blogIcon'

export * from './doubleQuoteRight'

export * from './alertSuccessIcon'
export * from './alertInfoIcon'
export * from './alertWarningIcon'
export * from './alertErrorIcon'
export * from './crossIcon'
export * from './loadingIcon'

export * from './homeIcon'
export * from './personIcon'
export * from './logoutIcon'
export * from './groupIcon'
export * from './group3Icon'
export * from './filterIcon'
export * from './mailIcon'
export * from './articleIcon'
export * from './searchIcon'
export * from './cartIcon'

export * from './heartIcon'
export * from './listIcon'
export * from './giftIcon'
export * from './gridIcon'
export * from './dashboardIcon'
export * from './starIcon'
export * from './menuIcon'
export * from './settingsIcon'
export * from './bellIcon'

export * from './googleIcon'
export * from './githubIcon'
export * from './linkedInIcon'
export * from './twitterIcon'
export * from './facebookIcon'
export * from './whatsAppIcon'
export * from './youtubeIcon'
export * from './instragramIcon'

export * from './arrowRightIcon'
export * from './arrowLeftIcon'
export * from './arrowUpIcon'
export * from './arrowDownIcon'
export * from '@/icons/angleLeft'
export * from '@/icons/angleRight'
export * from '@/icons/angleUp'
export * from '@/icons/angleDown'

export * from './rightAngleIcon'

export * from './downloadIcon'
export * from './cloudUploadIcon'

export * from './plusIcon'
export * from './addPlusIcon'
export * from './minusIcon'
export * from './multiplyIcon'
export * from './divisionIcon'
export * from './deleteIcon'
export * from './deleteOutlinedIcon'
export * from './editIcon'

export * from './alignLeft'
export * from './alignRight'
export * from './alignCenter'
export * from './alignJustify'

export * from './messageIcon'
export * from './likeIcon'
export * from './dislikeIcon'

export * from './playIcon'
export * from './forwardIcon'

export * from './accountIcon'
export * from './monitorPiIcon'
export * from './serviceIcon'
export * from './page'
export * from './metadata'
export * from './notificationIcon'
export * from './cameraIcon'


export * from './eyeOpenIcon'
export * from './eyeCloseIcon'