export * from '@/pages/dashboard/home'
export * from '@/pages/dashboard/portfolio/portfolio'
export * from '@/pages/dashboard/service'
export * from '@/pages/dashboard/customer'
export * from '@/pages/dashboard/notification'
export * from '@/pages/dashboard/setting'