import { Footer, Header } from '@/components'
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Product Layout | ",
  description: "Generated by create next app",
}

type Props = {
	children: React.ReactNode
}
const ProductLayout = ({ children }: Props) => {

	return (
		<div className=''>
		<Header />
		{children}
		{/* <Footer /> */}
		</div>
	)
}
export default ProductLayout
