import type { Metadata } from "next"
import { Footer, Header, SubHeader } from '@/components'


export const metadata: Metadata = {
  title: "Home Layout ",
  description: "Generated by create next app",
}

type Props = {
	children: Readonly<React.ReactNode>
}

const HomeLayout = ({ children }: Props) => {
  return (
		<div className=''>
			<Header />
			{/* <SubHeader /> */}
			{children}
			<Footer />
		</div>
  )
}
export default HomeLayout