import type { Metadata } from "next"
import Link from 'next/link'
import { HeroComponent, OfferComponent, ProductComponent, SearchWithFilter } from '@/components'
import { Button } from '@/components/mui'
import { heroItems } from '@/data/home'
import { DayBlock, DayHeading } from '@/components/home'


const productItems = [
	{ title: 't-shart for Man lorem lorem lorem', rating: 4, price: '$5.00', image: '/images/headphone.jpg', path: '/product/1' },
	{ title: 't-shart for Kid', rating: 5, price: '$8.00', image: '/images/headphone.jpg', path: '/product/2' },
	{ title: 'Skaff for wemon', rating: 5, price: '$5.00', image: '/images/headphone.jpg', path: '/product/3' },
	{ title: 't-shart for women', rating: 3, price: '$7.00', image: '/images/headphone.jpg', path: '/product/4' },
]


export const metadata: Metadata = {
  title: "Home Page | ",
  description: "Generated by create next app",
}

const Home = () => {

	return (
		<div className='min-h-screen w-full container mx-auto flex flex-col gap-4 px-2 md:px-0'>

			{/* Block-1: Search bar for mobile view only */}
			{/* <div data-name='search bar for mobile view' className='md:hidden grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 my-4'>
				<SearchWithFilter className='col-start-1 md:col-start-3' />
			</div> */}

			{/* Block-2: hero image */}
			{/* <div data-name='hero-image' className='grid grid-cols-1 md:grid-cols-2 gap-4'>
				<HeroComponent {...heroItems[0]} />
				<HeroComponent {...heroItems[1]} className='hidden md:block' />
			</div> */}

		</div>
	)
}
export default Home
